import React, { Fragment } from 'react';
import img1 from "../images/img1.jpg"
import img3  from "../images/img3.jpg"
import FactNumber from '../FactNumber';
import BrandLink from "../BrandLink";
import e from "../images/e.jpg"

const Aboutme = () => {
    return (
        <Fragment>
           
    
  
            <div style={{display:"flex" ,alignItems:"center" ,textShadow:"10px 10px red" }}  className="text-warning" >
                <div className="relative my-20 mx-auto">
                    <div className="absolute bg-yellow h-14 rounded-full top-0 w-14 -z-1"></div>
                    <BrandLink classes="text-6xl ml-5" />
                </div>
            </div>
            <div><img src={e} className='w-100'></img></div>
            <div className=" text-justify py-5">
                <div className="mx-auto w-2/3">
                    <h1 className='text-danger text-center'>About our services </h1>
                    <p className="mb-4 text-warning text-center" style={{textShadow:"1px 1px red"}} >
                        Welly is the leading premium beauty platform in Europe. Offering more than 130,000 beauty and
                        lifestyle products in online shops, the beauty marketplace and more than 2,000 stores, Welly
                        inspires customers to live their own kind of beauty by a previously unparalleled assortment.
                    </p>
                    <p className="text-warning"  style={{textShadow:"1px 1px red"}}>
                        The continued expansion of the fast-growing e‑commerce business is the focus of the
                        <span className="font-krona"> #forwardbeauty</span>. DigitalFirst strategy programme. In fiscal
                        year 2019/2020, Welly generated sales of 3.2 billion euros in the areas of perfumery, decorative
                        cosmetics, skin and hair care as well as nutritional supplements and accessories.
                        <span className="font-krona"> #letsdobeautiful</span>
                    </p>
                </div>
            </div>
          <div className='container'>
             <div className='row'>
                <div className='col-md'>
                <div className='d-flex justify-content-evenly margin:auto'>
                    
                    <img src={img1} className='w-20 ml-5 mt-5'  style={{textShadow:"10px 10px red"}}>
                        
                        </img><img src={img3} className='w-20 mt-5'  style={{textShadow:"10px 10px red"}}></img></div>
            <div className='d-flex justify-content-evenly margin:auto'><img src={img1} className='w-20 mt-5'  style={{textShadow:"10px 10px red"}}></img><img src={img3} className='w-20 mt-5'  style={{textShadow:"10px 10px red"}}></img></div>
            
            
                </div>
             </div>
          </div>
          
            <div  className="text-warning">
                <div className="flex flex-col md:flex-row space-y-10 md:space-y-0 py-10 w-3/4 mx-auto">
                    {/* Facts and figures */}
                    <FactNumber
                      
                        number="20,000"
                        title="Beauty Experts"
                        description="strive to make their customers more beautiful and thus happier"
                    />
                    <FactNumber
                     
                        number="3.2"
                        title="Billion Euros"
                        description="revenue was generated by Douglas in the 2019/20 financial year"
                    />
                    <FactNumber
                    
                        number="130,000"
                        title="Care Products"
                        description="because we care about you in online shops, and in stores"
                    />
                </div>
            </div>
            <div className="text-center w-2/3 mx-auto my-20 text-warning"  style={{textShadow:"1px 1px red"}}>
                <h4 className="font-krona mb-4"  style={{textShadow:"1px 1px red"}}>Imprint</h4>
                <p>Welly Inc. Welly-Street 7-11 40235 Welland</p>
                <p>
                    You can reach us by email at: service@welly.wellly. Our deliveries go out every Sunday evening so
                    you can get them as early in the week as possible
                </p>
            </div>
        </Fragment>
    );
};

export default Aboutme;

